import os
import json
import boto3
from datetime import datetime

# Initialize the SES client
# The region can be configured as an environment variable in Lambda,
# or it will default to the region where the Lambda function is deployed.
ses_client = boto3.client('ses')

def lambda_handler(event, context):
    """
    AWS Lambda function to generate a simple daily report and send it via email.

    This function is typically triggered by an Amazon EventBridge (CloudWatch Events)
    scheduled rule (e.g., daily at a specific time).

    Args:
        event (dict): The event data from the trigger. For scheduled events,
                      this contains metadata about the scheduled invocation.
        context (object): The runtime context of the Lambda function.
    """
    print(f"Lambda function invoked at: {datetime.now()}")
    print(f"Event received: {json.dumps(event)}")

    # --- Configuration ---
    # Replace with your verified sender email address in SES.
    # This email must be verified in SES to send emails.
    SENDER_EMAIL = os.environ.get('SENDER_EMAIL', 'your-verified-sender@example.com')
    # Replace with the recipient email address(es).
    # For production, consider storing this in AWS Secrets Manager or Parameter Store.
    RECIPIENT_EMAILS = os.environ.get('RECIPIENT_EMAILS', 'your-recipient@example.com').split(',')

    # Simple report content (you would replace this with actual data fetching/processing)
    report_date = datetime.now().strftime("%Y-%m-%d")
    report_subject = f"Daily Workspace Automation Report - {report_date}"

    # --- Simulate fetching/generating report data ---
    # In a real-world scenario, you might:
    # - Query a database (e.g., DynamoDB, RDS)
    # - Call another API
    # - Read data from an S3 bucket
    # - Perform some calculations

    # For this example, we'll create a static report message.
    report_body_html = f"""
    <html>
    <head></head>
    <body>
        <h1>Daily Workspace Automation Summary for {report_date}</h1>
        <p>This is an automated report generated by an AWS Lambda function.</p>
        <p>Here's a quick overview of today's activities:</p>
        <ul>
            <li><strong>Automated Task 1:</strong> Successfully completed.</li>
            <li><strong>Automated Task 2:</strong> Processed 15 new files.</li>
            <li><strong>System Health Check:</strong> All systems nominal.</li>
        </ul>
        <p>For more details, please refer to the system logs.</p>
        <p>Best regards,</p>
        <p>Your Automation Bot</p>
    </body>
    </html>
    """

    report_body_text = f"""
    Daily Workspace Automation Summary for {report_date}

    This is an automated report generated by an AWS Lambda function.

    Here's a quick overview of today's activities:
    - Automated Task 1: Successfully completed.
    - Automated Task 2: Processed 15 new files.
    - System Health Check: All systems nominal.

    For more details, please refer to the system logs.

    Best regards,
    Your Automation Bot
    """

    # --- Send the email using SES ---
    try:
        response = ses_client.send_email(
            Source=SENDER_EMAIL,
            Destination={
                'ToAddresses': RECIPIENT_EMAILS
            },
            Message={
                'Subject': {
                    'Data': report_subject,
                    'Charset': 'UTF-8'
                },
                'Body': {
                    'Html': {
                        'Data': report_body_html,
                        'Charset': 'UTF-8'
                    },
                    'Text': {
                        'Data': report_body_text,
                        'Charset': 'UTF-8'
                    }
                }
            }
        )
        print(f"Email sent successfully! Message ID: {response['MessageId']}")
        return {
            'statusCode': 200,
            'body': json.dumps('Report email sent successfully!')
        }
    except Exception as e:
        print(f"Error sending email: {e}")
        return {
            'statusCode': 500,
            'body': json.dumps(f'Error sending report email: {str(e)}')
        }
